name: RaphaZombie
version: '${project.version}'
main: com.github.idimabr.raphazombie.RaphaZombie
api-version: 1.18
authors: [ iDimaBR ]
softdepend: [PlaceholderAPI]
commands:
  infect:
    aliases: [infectzombie, iz]
