MySQL:
  Host: 'localhost'
  Database: 'raphazombie'
  Username: 'root'
  Password: ''

Mundo: "mundo"

Chance:
  Membro: 25
  VIP: 15

Efeitos:
  Confusao:
    Tempo: 15
    Nivel: 1

InventarioConfirmar:
  Titulo: "Deseja armazenar esse Astatos?"
  Comandos:
  - "/paycoins %player% 300"

Crafting:
  Morfina:
    Recipe:
      Row1: "AAA"
      Row2: "AAA"
      Row3: "   "
    Ingredientes:
      - "A;SUGAR"
  KitMedico:
    Recipe:
      Row1: "AAA"
      Row2: "BBB"
      Row3: "   "
    Ingredientes:
      - "A;SUGAR"
      - "B;REDSTONE"
  Soro:
    Recipe:
      Row1: " A "
      Row2: " B "
      Row3: "   "
    Ingredientes:
      - "A;CACTUS"
      - "B;BOWL"

Itens:
  Morfina:
    Nome: "§aMorfina"
    Material: "PAPER"
    Lore:
    - "§7Utilize para curar sua infecção."
  KitMedico:
    Nome: "§aKit Médico"
    Material: "REDSTONE_BLOCK"
    Lore:
    - "§7Utilize para curar seu sangramento."
  Soro:
    Nome: "§aSoro"
    Material: "POTION"
    Lore:
    - "§7Utilize para saciar sua sede."
  DropZombie:
    Nome: "§aAstato"
    Material: "DOUBLE_PLANT"
    Lore:
    - "§7Drop de Chernobyl"
